import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";

import { primary_font } from "@/lib/fonts";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", primary_font.className)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
